### ISSUE TITLE
Rename filename functionality

### ISSUE THREAD

**Issue by sulenchy** [NoroffFEU/yeetsheet#198]
**User Story:**

As a user, I want the ability to rename an existing file so that I can easily update the file's name to better reflect its content or purpose.

**Acceptance Criteria:**

- A "Rename File" option is available for each file.
- When the user selects this option, the current file name becomes editable.
- The user can input a new name and confirm the change.
- The file list updates immediately with the new name once confirmed.
- The renaming action does not affect the file’s contents or any associated data.

**Comment by ttowntom** [comment]
Clearification: "Project" and "File" is the same this
![Image](https://github.com/user-attachments/assets/8e30f749-7709-4613-a4cd-9f7361b3d814)

This functionality was therefore fixed in PR #147 

For this ticket:

- Make sure the "Name of the file" area above the sheet reflects the change made to "Project name" on save
![Image](https://github.com/user-attachments/assets/ba727601-b882-4903-91e8-807815a6ee42)
