### ISSUE TITLE
Fix searchbar width

### ISSUE THREAD

**Issue by DanielEkerhovd** [NoroffFEU/yeetsheet#236]
The searchbar is taking too much space on small screens. Figure out a way to make it responsive: 

You could: 

- Use flex-wrap and make it take the whole width on smaller screens
- Other ideas are welcome

NOTE!!
There is another task about moving the darkmode button, so you do not need to work on that.

**Comment by jonhenrikaavitsland** [comment]
@robfil50219 Thank you for your work. 
I would point out that you should keep existing design files in mind so that we retain the desktop layout while also implementing a mobile design. 
The Pr was merged successfully, and a new ticket will be created to fix the layout issue. 
This ticket is now closed.
